# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
branches:
  only: # Only kick off CI for master and potential merges to master from within PRs
    - master
matrix:
  allow_failures:
    - julia: nightly
after_success:
  - julia -e 'using Pkg; import Meshing; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'

